grails-app/controllers/linksharing/DashboardController.groovy
package linksharing

import com.ttnd.linksharing.dto.TopicDTO
import com.ttnd.linksharing.dto.UserDTO
import com.ttnd.linksharing.User
import com.ttnd.linksharing.resource.Resource

class DashboardController {

    TopicService topicService;
    ResourceService resourceService;
    def index() {
        User user = session.user;
        List<TopicDTO> subscribedTopics;
        List<TopicDTO> trendingTopics;
        List<Resource> unreadResourceList;
        int totalUnreadPostCount;
        UserDTO userDTO;
        if(user) {
            subscribedTopics = topicService.getSubscribedTopicList(user,0,5);
            trendingTopics =  topicService.getTrendingTopicList(user,0,5);
            unreadResourceList = resourceService.getUnreadResourceList(user,0,10);
            totalUnreadPostCount = resourceService.getTotalUnreadResourceCount(user);
            userDTO = new UserDTO(id: user.id,username: user.username,firstName: user.firstName,lastName: user.lastName,
                    profilePicPath: user.profilePicPath,admin: user.admin,active: user.active);
            userDTO.subscriptionCount = topicService.getTopicCount(user,"subscribed");
            userDTO.topicCount = topicService.getTopicCount(user,"created");
        }
        render(view: "dashboard",model: [user:userDTO, subscribedTopics:subscribedTopics, trendingTopics:trendingTopics, totalUnreadPostCount:totalUnreadPostCount, unreadResourceList:unreadResourceList])
    }

    def showInboxPosts(int offset,int max) {
        User user = session.user;
        render(view: 'template/_inbox',model: [resourceDTOList:resourceService.getUnreadResourceList(user,offset,max),
                                               totalRecords:resourceService.getTotalUnreadResourceCount(user)])
    }
}

grails-app/controllers/linksharing/ResourceController.groovy
package linksharing

import com.ttnd.linksharing.co.DocResourceCO
import com.ttnd.linksharing.co.LinkResourceCO
import com.ttnd.linksharing.dto.ResourceDTO
import com.ttnd.linksharing.dto.TopicDTO
import com.ttnd.linksharing.User
import com.ttnd.linksharing.resource.Resource

class ResourceController {

    ResourceService resourceService;
    TopicService topicService;

    def index() {}

    def createLinkResource(LinkResourceCO resourceCO) {
        if(resourceCO.validate()) {
            resourceCO.user = session.user;
            if(resourceService.createLinkResource(resourceCO)) {
                flash.message = "Link shared successfully in ${resourceCO.topicName}."
            } else {
                flash.error = "Some error occurred while sharing link."
            }
        } else {
            flash.error = "Please specify all mandatory fields."
        }
        redirect(controller: "dashboard",action: "index")
    }

    def createDocResource(DocResourceCO resourceCO) {
        if(resourceCO.validate()) {
            resourceCO.user = session.user;
            resourceCO.fileLocation = grailsApplication.config.file.location;
            if(resourceService.createDocResource(resourceCO)) {
                flash.message = "Document shared successfully in ${resourceCO.topicName}."
            } else {
                flash.error = "Some error occurred while sharing document."
            }
        } else {
            flash.error = "Please specify all mandatory fields."
        }
        redirect(controller: "dashboard",action: "index")
    }

    def toggleReadStatus(int postId,String event) {
        render (resourceService.resourceReadChange(session.user.id,postId,event))
    }

    def downloadFile(long resourceId) {
        Resource resource = resourceService.getDocResource(resourceId);
        def file = new File(resource.filePath);
        if (file.exists())
        {
            response.setContentType("application/octet-stream") // or or image/JPEG or text/xml or whatever type the file is
            response.setHeader("Content-disposition", "attachment;filename=\"${file.name}\"")
            response.outputStream << file.bytes
        }
        else {
            render "Error!"
        } // appropriate error handling
    }

    def visitUrl(long resourceId) {
        Resource resource = resourceService.getLinkResource(resourceId);
        if(resource.url) {
            redirect(url: resource.url)
        }
    }

    def showPostByTopic(long topicId,int offset,int max) {
        User user = session.user;
        int totalRecords;
        String topicName;
        topicName = resourceService.getTopicName(topicId);
        totalRecords = resourceService.getTotalResourceCount(topicId)
        render (view:'_showPostByTopic',model: [topicId:topicId, totalRecords:totalRecords,
                topicName:topicName, resourceDTOList: resourceService.getTopicResourceList(topicId,user,offset,max)])
    }

    def viewPost(long resourceId) {
        User user = session.user;
        List<TopicDTO> subscribedTopics = topicService.getSubscribedTopicList(user,0,5);
        List<TopicDTO> trendingTopics =  topicService.getTrendingTopicList(user,0,5);
        ResourceDTO resourceDTO = resourceService.getResource(resourceId,user);
        resourceDTO.rating = resourceService.getResourceRating(resourceId,user);
        render (view: 'viewPost',model: [user:user,post: resourceDTO,trendingTopics:trendingTopics,subscribedTopics:subscribedTopics])
    }

    def saveResourceRating(long resourceId,int score) {
        User user = session.user;
        render resourceService.saveResourceRating(resourceId,score,user);
    }

    def resourceDelete(long resourceId) {
        User user = session.user;
        String message = resourceService.deleteResource(resourceId,user);
        if(message) {
            flash.error = message;
            redirect(action: 'viewPost',params: [resourceId:resourceId])
        } else {
            flash.message = "Post deleted successfully."
            redirect(controller: 'dashboard',action: 'index')
        }
    }

    def editPost(long resourceId,String description) {
        User user = session.user;
        String message = resourceService.editResource(resourceId,description,user);
        if(message) {
            flash.error = message;
        }
        redirect(action: 'viewPost',params: [resourceId:resourceId])
    }

}

grails-app/views/dashboard/template/_inbox.gsp
<legend>Inbox</legend>
<div id="ajax-inbox-div">
    <g:each in="${resourceDTOList}" var="topicDTO">
        <g:include view="dashboard/template/_post.gsp" model="${[post:topicDTO]}"></g:include>
    </g:each>
</div>
<div class="pagination">
    <util:remotePaginate controller="dashboard" action="showInboxPosts" total="${totalRecords}" update="inbox-outer-div"
                         pageSizes="[10:'10 Per Page', 20: '20 Per Page', 50:'50 Per Page',100:'100 Per Page']"/>
</div>

grails-app/views/dashboard/template/_post.gsp
<div class="row-fluid bottom-border">
    <div class="span1 margin-vertical">
        <g:link controller="user" action="showUser" params="[userId:post.createdBy.id]">
            <img src="${post.createdBy.profilePicPath}" width="100%" onerror="this.src='/images/profile/user-default.png'">
        </g:link>
    </div>
    <div class="span11 margin-vertical">
        <div class="row-fluid">
            <g:link controller="user" action="showUser" params="[userId:post.createdBy.id]">
                ${post.createdBy.firstName}&nbsp;${post.createdBy.lastName}
            </g:link>
            <label class="gray-text" style="display: inline-block;padding: 0 20px;">@${post.createdBy.username}</label>
            <g:link controller="topic" action="viewOneTopic" params="${[topicId:post.topicId]}" class="pull-right">${post.topicName}</g:link>
        </div>
        <div class="row-fluid">
            ${post.description}
        </div>
        <div class="row-fluid">
            <g:if test="${session.user}">
                <g:link controller="resource" action="${post.linkAction}" params="${[resourceId:post.id]}" target="_blank">
                    ${post.linkText}
                </g:link>
                <a class="margin-horizontal read" event="${post.isRead?"unread":"read"}" postId="${post.id}">
                    Mark as ${post.isRead?"unread":"read"}
                </a>
            </g:if>
            <g:link controller="resource" action="viewPost" params="${[resourceId: post.id]}">View Post</g:link>
        </div>
    </div>
</div>

grails-app/views/dashboard/template/_topic.gsp
<div class="bottom-border topicDiv" topicId="${topicDTO.id}">
<div class="row-fluid margin-vertical">
    <div class="row-fluid">
        <div class="span2">
            <g:link controller="user" action="showUser" params="[userId:topicDTO.createdBy.id]">
                <img src="${topicDTO.createdBy.profilePicPath}" width="100%"
                     onerror="this.src = '/images/profile/user-default.png'">
            </g:link>
        </div>

        <div class="span10">
            <div class="row-fluid topicNameDisplay">
                <g:if test="${linkType}">
                    <a href="javascript:void(0);" class="showPostAjax">
                        ${topicDTO.name}
                    </a>
                </g:if>
                <g:else>
                    <g:link controller="topic" action="viewOneTopic" params="${[topicId: topicDTO.id]}">
                            ${topicDTO.name}
                    </g:link>
                </g:else>
            </div>

            <div class="row-fluid topicNameEdit" style="display: none;">
                <input type="text" name="topicName" value="${topicDTO.name}">
                <a href="javascript:void(0);" class="saveTopicName">
                    <i class="icon-ok" title="Save" data-placement="bottom"></i>
                </a>
                <a href="javascript:void(0);" class="cancelTopicName">
                    <i class="icon-remove" title="Cancel" data-placement="bottom"></i>
                </a>
            </div>

            <div class="row-fluid">
                <div class="span4">
                    <label class="gray-text">@${topicDTO.createdBy.username}</label>
                    <g:if test="${session.user}">
                        <g:if test="${topicDTO.createdBy.id == session.user.id}">
                            <label class="gray-text">Subscribed</label>
                        </g:if>
                        <g:else>
                            <g:if test="${topicDTO.loggedInUserSeriousness}">
                                <a class="subscribe" event="unsubscribe">
                                    Unsubscribe
                                </a>
                            </g:if>
                            <g:else>
                                <a class="subscribe" event="subscribe">
                                    Subscribe
                                </a>
                            </g:else>
                        </g:else>
                    </g:if>
                </div>

                <div class="span4">
                    <label class="gray-text">Subscriptions</label>
                    <g:link controller="topic" action="viewOneTopic" params="${[topicId: topicDTO.id]}">
                        ${topicDTO.subscriberCount}
                    </g:link>
                </div>

                <div class="span4">
                    <label class="gray-text">Posts</label>
                    <g:link controller="topic" action="viewOneTopic" params="${[topicId: topicDTO.id]}">
                        ${topicDTO.resourceCount}
                    </g:link>
                </div>
            </div>
            <g:if test="${session.user && (session.user.admin || (topicDTO.createdBy.id == session.user.id))}">
                <div class="row-fluid">
                    <g:select optionKey="value" value="${topicDTO.visibility.value}"
                              class="form-control topicVisibility" style="width: auto;"
                              name="visibility" from="${com.ttnd.linksharing.enums.Visibility.values()}"/>
                    <g:if test="${topicDTO.loggedInUserSeriousness}">
                        <g:select optionKey="value" value="${topicDTO.loggedInUserSeriousness.value}"
                                  class="form-control topicSeriousness" style="width: auto;"
                                  name="seriousness" from="${com.ttnd.linksharing.enums.Seriousness.values()}"/>
                        <a href="#send-invite" data-toggle="modal" class="sendInviteSingle">
                            <i class="icon-envelope" title="Send Invite" data-placement="bottom"></i>
                        </a>
                    </g:if>
                    <a href="javascript:void(0);" class="editTopic">
                        <i class="icon-edit" title="Edit topic" data-placement="bottom"></i>
                    </a>
                    <a href="javascript:void(0);" class="deleteTopic">
                        <i class="icon-trash" title="Delete topic" data-placement="bottom"></i>
                    </a>
                </div>
            </g:if>
            <g:else>
                <div class="row-fluid">
                <g:if test="${topicDTO.loggedInUserSeriousness}">
                    <g:select optionKey="value" value="${topicDTO.loggedInUserSeriousness.value}"
                              class="form-control topicSeriousness" style="width: auto;"
                              name="seriousness" from="${com.ttnd.linksharing.enums.Seriousness.values()}"/>
                    <a href="#send-invite" data-toggle="modal">
                        <i class="icon-envelope" title="Send Invite" data-placement="bottom"></i>
                    </a>
                </g:if>
                </div>
            </g:else>
        </div>
    </div>

    <div class="row-fluid">
        <div class="alert-success row-fluid text-center" style="display: none;font-size: 10px;">
        </div>

        <div class="alert-danger row-fluid text-center" style="display: none;font-size: 10px;">
        </div>
    </div>
</div>
</div>