grails-app/domain/com/ttnd/linksharing/Subscription.groovy
package com.ttnd.linksharing

import com.ttnd.linksharing.enums.Seriousness
import groovy.transform.ToString

/**
 * Created by niranjan on 14/1/16.
 */
@ToString
class Subscription {
    Seriousness seriousness;
    Date dateCreated;
    Date lastUpdated;

    static belongsTo = [topic:Topic,user:User]

    static mapping = {
        seriousness enumType: 'ordinal'
    }
}

grails-app/domain/com/ttnd/linksharing/Topic.groovy
package com.ttnd.linksharing

import com.ttnd.linksharing.enums.Visibility
import com.ttnd.linksharing.resource.Resource
import groovy.transform.ToString

/**
 * Created by niranjan on 14/1/16.
 */
@ToString
class Topic {
    String name;
    Visibility visibility;
    Date dateCreated;

    Date lastUpdated;
    static belongsTo = [createdBy:User]
    static hasMany = [subscriber:Subscription,resource:Resource]

    static mapping = {
        visibility enumType: 'ordinal'
    }

    static constraints = {
        name (unique: true)
    }


}

grails-app/controllers/linksharing/ResourceController.groovy
package linksharing

import com.ttnd.linksharing.co.DocResourceCO
import com.ttnd.linksharing.co.LinkResourceCO
import com.ttnd.linksharing.dto.ResourceDTO
import com.ttnd.linksharing.dto.TopicDTO
import com.ttnd.linksharing.User
import com.ttnd.linksharing.resource.Resource

class ResourceController {

    ResourceService resourceService;
    TopicService topicService;

    def index() {}

    def createLinkResource(LinkResourceCO resourceCO) {
        if(resourceCO.validate()) {
            resourceCO.user = session.user;
            if(resourceService.createLinkResource(resourceCO)) {
                flash.message = "Link shared successfully in ${resourceCO.topicName}."
            } else {
                flash.error = "Some error occurred while sharing link."
            }
        } else {
            flash.error = "Please specify all mandatory fields."
        }
        redirect(controller: "dashboard",action: "index")
    }

    def createDocResource(DocResourceCO resourceCO) {
        if(resourceCO.validate()) {
            resourceCO.user = session.user;
            resourceCO.fileLocation = grailsApplication.config.file.location;
            if(resourceService.createDocResource(resourceCO)) {
                flash.message = "Document shared successfully in ${resourceCO.topicName}."
            } else {
                flash.error = "Some error occurred while sharing document."
            }
        } else {
            flash.error = "Please specify all mandatory fields."
        }
        redirect(controller: "dashboard",action: "index")
    }

    def toggleReadStatus(int postId,String event) {
        render (resourceService.resourceReadChange(session.user.id,postId,event))
    }

    def downloadFile(long resourceId) {
        Resource resource = resourceService.getDocResource(resourceId);
        def file = new File(resource.filePath);
        if (file.exists())
        {
            response.setContentType("application/octet-stream") // or or image/JPEG or text/xml or whatever type the file is
            response.setHeader("Content-disposition", "attachment;filename=\"${file.name}\"")
            response.outputStream << file.bytes
        }
        else {
            render "Error!"
        } // appropriate error handling
    }

    def visitUrl(long resourceId) {
        Resource resource = resourceService.getLinkResource(resourceId);
        if(resource.url) {
            redirect(url: resource.url)
        }
    }

    def showPostByTopic(long topicId,int offset,int max) {
        User user = session.user;
        int totalRecords;
        String topicName;
        topicName = resourceService.getTopicName(topicId);
        totalRecords = resourceService.getTotalResourceCount(topicId)
        render (view:'_showPostByTopic',model: [topicId:topicId, totalRecords:totalRecords,
                topicName:topicName, resourceDTOList: resourceService.getTopicResourceList(topicId,user,offset,max)])
    }

    def viewPost(long resourceId) {
        User user = session.user;
        List<TopicDTO> subscribedTopics = topicService.getSubscribedTopicList(user,0,5);
        List<TopicDTO> trendingTopics =  topicService.getTrendingTopicList(user,0,5);
        ResourceDTO resourceDTO = resourceService.getResource(resourceId,user);
        resourceDTO.rating = resourceService.getResourceRating(resourceId,user);
        render (view: 'viewPost',model: [user:user,post: resourceDTO,trendingTopics:trendingTopics,subscribedTopics:subscribedTopics])
    }

    def saveResourceRating(long resourceId,int score) {
        User user = session.user;
        render resourceService.saveResourceRating(resourceId,score,user);
    }

    def resourceDelete(long resourceId) {
        User user = session.user;
        String message = resourceService.deleteResource(resourceId,user);
        if(message) {
            flash.error = message;
            redirect(action: 'viewPost',params: [resourceId:resourceId])
        } else {
            flash.message = "Post deleted successfully."
            redirect(controller: 'dashboard',action: 'index')
        }
    }

    def editPost(long resourceId,String description) {
        User user = session.user;
        String message = resourceService.editResource(resourceId,description,user);
        if(message) {
            flash.error = message;
        }
        redirect(action: 'viewPost',params: [resourceId:resourceId])
    }

}

grails-app/controllers/linksharing/TopicController.groovy
package linksharing

import com.ttnd.linksharing.Invitation
import com.ttnd.linksharing.Topic
import com.ttnd.linksharing.User
import com.ttnd.linksharing.co.TopicCO
import com.ttnd.linksharing.dto.TopicDTO

class TopicController {

    TopicService topicService;
    ResourceService resourceService;

    def index() {}

    def createTopic(TopicCO topicCO) {
        if(topicCO.validate()) {
            if(topicService.findTopicByName(topicCO.topicName)) {
                flash.error = "Topic with same name already exists"
            } else {
                topicCO.user = session.user;
                Topic topic = topicService.createTopic(topicCO);
                if(topic) {
                    flash.message = "Topic created and subscribed successfully."
                } else {
                    flash.error = "Some error occurred while creating topic."
                }
            }
        } else {
            flash.error = "Please provide all mandatory fields to create topic."
        }
        redirect(controller: "dashboard",action: "index")
    }

    def isTopicAvailable(String topicName) {
        println("topicName :: ${topicName}")
        if(topicName) {
            render topicService.findTopicByName(topicName)?false:true
        } else {
            render "Please provide topic name."
        }
    }

    def sendInviteMail(String inviteEmail,long inviteTopic) {
        User user = session.user;
        String message = topicService.checkForOtherInvites(inviteEmail,inviteTopic);
        if(message) {
            flash.message = message;
        } else {
            Invitation invitation = topicService.sendTopicInviteMail(inviteEmail,inviteTopic,user)
            if(invitation) {
                flash.message = "Invitation sent to ${inviteEmail}."
            } else {
                flash.error = "Some error occurred during invitation."
            }
        }
        redirect(controller: "dashboard",action: "index")
    }

    def viewOneTopic(long topicId) {
        User user = session.user;
        TopicDTO topicDTO = topicService.getOneTopic(topicId,user)
        int resourceCount = resourceService.getTotalResourceCount(topicId)
        List<TopicDTO> subscribedTopics = topicService.getSubscribedTopicList(user,0,5);
        render (view: 'viewOneTopic', model: [topic: topicDTO,totalResources:resourceCount,subscribedTopics:subscribedTopics])
    }

    def viewAllTopics(String type,long userId) {
        User user = session.user;
        String heading;
        int totalTopicCount = topicService.getTotalTopicCount(user,"subscribed");
        List<TopicDTO> topicDTOList = [];
        if("subscribed".equals(type)) {
            topicDTOList = topicService.getSubscribedTopicList(user,0,10);
            heading = "All Subscriptions";
        } else if ("user".equals(type)){
            topicDTOList = topicService.getCreatedTopicList(User.load(userId),0,10)
            heading = "All Topics by "+topicService.getUserFullName(userId);
        }
        List<TopicDTO> subscribedTopics = topicService.getSubscribedTopicList(user,0,5);

        render(view: "/admin/showTopics",model:[heading:heading,totalTopicCount:totalTopicCount,topicDTOList:topicDTOList,subscribedTopics:subscribedTopics])
    }

    def topicSubscriptionChange(long topicId,String event) {
        render (topicService.topicSubscriptionChange(topicId,session.user,event))
    }

    def topicVisibilityChange(long topicId,int visibility) {
        render (topicService.topicVisibilityChange(topicId,visibility))
    }

    def topicSeriousnessChange(long topicId,int seriousness) {
        render (topicService.topicSeriousnessChange(topicId,session.user,seriousness))
    }

    def topicInviteUser(long topicId,String email) {
        render (topicService.topicInviteUser(topicId,session.user,email))
    }

    def topicNameEdit(long topicId,String topicName){
        render (topicService.topicNameEdit(topicId,topicName,session.user))
    }

    def topicDelete(long topicId) {
        render (topicService.topicDelete(topicId))
    }

}

grails-app/views/topic/viewOneTopic.gsp
<%--
  Created by IntelliJ IDEA.
  User: niranjan
  Date: 23/1/16
  Time: 6:07 PM
--%>

<%@ page contentType="text/html;charset=UTF-8" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="custom">
</head>

<body>
<div class="container" style="margin-bottom: 20px;">
    <g:include view="common/_header.gsp"></g:include>
    <g:include view="common/_message.gsp"></g:include>
    <div class="row-fluid">
        <div class="span5">
            <div class="navbar-inner" style="margin-bottom: 20px;">
                <legend>Topic : "${topic.name}"</legend>
                <g:include view="dashboard/template/_topic.gsp" model="${[topicDTO: topic]}"></g:include>
            </div>

            <div class="navbar-inner" style="margin-bottom: 20px;">
                <legend><b>Users :</b>"${topic.name}"</legend>
                <g:each in="${topic.subscriberList}" var="user">
                    <div class="row-fluid bottom-border margin-vertical">
                        <div class="span2 margin-vertical">
                            <g:link controller="user" action="showUser" params="[userId: user.id]">
                                <img src="${user.profilePicPath}" width="100%"
                                     onerror="this.src = '/images/profile/user-default.png'">
                            </g:link>
                        </div>

                        <div class="span10 margin-vertical">
                            <div class="row-fluid" style="margin-bottom: 10px">
                                <g:link controller="user" action="showUser" params="[userId: user.id]">
                                    ${user.firstName} ${user.lastName}
                                </g:link>
                                <label class="gray-text">@${user.username}</label>
                            </div>

                            <div class="row-fluid" style="line-height: 5px;">
                                <div class="span6">
                                    <label class="gray-text">Subscriptions</label>
                                    <label class="gray-text">
                                        ${user.subscriptionCount}
                                    </label>
                                </div>

                                <div class="span6">
                                    <label class="gray-text">Topics</label>
                                    <label class="gray-text">
                                        ${user.topicCount}
                                    </label>
                                </div>
                            </div>
                        </div>
                    </div>
                </g:each>
            </div>
        </div>

        <div class="span7">
            <div class="navbar-inner" id="ajax-post-outer-div" style="margin-bottom: 20px;">
                <g:include view="resource/_showPostByTopic.gsp"
                           model="${[totalRecords: totalResources, resourceDTOList: topic.resourceList, topicId: topic.id]}"></g:include>
            </div>
        </div>
    </div>
    <g:include view="dashboard/popup/createTopic.gsp"></g:include>
    <g:include view="dashboard/popup/inviteUser.gsp"></g:include>
    <g:include view="dashboard/popup/createLink.gsp"></g:include>
    <g:include view="dashboard/popup/createDoc.gsp"></g:include>
</div>
</body>
</html>